create table
  public.global_inventory (
    id bigint generated by default as identity,
    gold integer null default 0,
    num_red_ml integer null default 0,
    num_green_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potions (
    id integer generated by default as identity,
    sku text null default '""'::text,
    name text null default '""'::text,
    quantity integer null default 0,
    price integer null default 0,
    potion_type jsonb null default '[0, 0, 0, 0]'::jsonb,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    cart_id integer generated by default as identity,
    customer text null default ''::text,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    item_id integer generated by default as identity,
    cart_id integer null,
    quantity integer null default 0,
    potion_id integer null,
    constraint cart_items_pkey primary key (item_id),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id) on update cascade on delete cascade,
    constraint public_cart_items_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;